### ISSUE TITLE
Top level license in README is said to be LGPL, but there is also GPL-licensed code and several other licenses

### ISSUE THREAD

**Issue by pombredanne** [zkoss/zkgmapsz#5]
The README states that this repo is under the LGPL (no version specified) but there are files under various versions of the LGPL and GPL. It would be nice if you could clarify what is the license for this repo.

**Comment by bduranc** [comment]
+1 on @pombredanne's question. 

> The README states that this repo is under the LGPL (no version specified) but there are files under various versions of the LGPL and GPL. It would be nice if you could clarify what is the license for this repo.

**Comment by cor3000** [comment]
I transferred the issue to https://tracker.zkoss.org/browse/ZKGMAPS-22

The correct license should be GPL while it is possible to obtain a commercial license (which is included in ZK EE automatically).

https://www.zkoss.org/zkdemo/reporting/google_map

**Comment by pombredanne** [comment]
@cor3000 thank you ++ for the clarification!

**Comment by pombredanne** [comment]
I reckon this has been fixed with https://github.com/zkoss/zkgmapsz/commit/3c370c828e46b2547bd29adf2acc53cebe6e4b20
