### ISSUE TITLE
GMaps problem (sometimes) when it's too much libraries on the page

### ISSUE THREAD

**Issue by epilefreyes** [zkoss/zkgmapsz#8]
**File: web\js\gmaps\Gmaps.js**
_Line 627:_
`if (window.google && (!window.google.load  || window.google.loader.LoadFailure)) {`

Change to:

`if (window.google && (!window.google.load  || window.google.load.LoadFailure)) {`

**Reason:** 
"window.google.loader" doesn't exists in current Google API Version.  It is window.google.load only.

**Comment by mduchemin** [comment]
Hi @epilefreyes 
Good find!

Thanks for the suggestion.
Tested and include in the latest FL available in maven and in the releases in this repo.
Let me know if you encounter any issue while testing.

**Comment by mduchemin** [comment]
resolved in https://github.com/zkoss/zkgmapsz/commit/7fa62d4c2c3de6a34ead7a44b4eaa39e4a0b3ab5

**Comment by cor3000** [comment]
fixed in version 3.1.0
